package edu.jiangxin.zhihu.core;

public enum Kind {
	
	SOMETOPIC_FOLLOWERS,
	SOMEQUESTION_FOLLOWERS,
	SOMEPEOPLE_FOLLOWEES,
	SOMEPEOPLE_FOLLOWERS,
	SOMEPEOPLE_COLUMNS,
	SOMEPEOPLE_TOPICS,
	UNKNOWN
}
